"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

APP = ['marker_web/ui.py']

OPTIONS = {'argv_emulation': True,
           'strip': True,
           'iconfile': 'extra/icon.icns', # uncomment to include an icon
           'includes': ['WebKit', 'Foundation', 'webview'],
           'packages': [ 'marker_web' ]}

packages = find_packages(".")
# print(packages)

setup(
    name="Marker",
    packages=packages,  # include all packages under src
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
