<template>
  <div class="waiting-app">
    Authentication is enabled.<br> 
    Please enter the token generated by the server to access to marker.
    <div style="height:100px">
    <v-text-field
      hide-details
      class="my-4"
      v-model="auth_token"
      label="Authorization Token"
      placeholder="Enter token here"
      autocomplete="off"
      clearable
      outlined
    ></v-text-field>
    </div>
    <v-btn @click="clickButton">
      Continue
    </v-btn>
  </div>
</template>

<script>
import markerAPI from '@/lib/marker/API'

export default {
  name: "Auth",
  data: () => ({
    auth_token: ""
  }),
  methods: {
    async clickButton() {
      $cookies.set('auth', this.auth_token);
      this.$store.commit('setNeedAuth', false);
      await this.$store.dispatch('fetchMarkerState',
        () => markerAPI.getMarkerState()
      );
      this.$router.go("/")
    }
  }
}
</script>

<style scoped>
.v-input {
  height:100px;
  padding: 0;
  width: 600px;
}
</style>